[package]
name = "yellow-pitaya"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]

[dependencies]
cairo-rs = "0.7"
docopt = "0.8"
env_logger = "0.4"
glib = "0.8"
gdk = "0.11"
gdk-sys = "0.9"
log = "0.3"
redpitaya-scpi = "0.27"
relm = "0.17"
relm-derive = "0.17"
serde = "1.0"
serde_derive = "1.0"

[dependencies.gtk]
version = "0.7"
features = ["v3_16"]
