[package]
name = "yellow-pitaya"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]

[dependencies]
env_logger = "0.3"
glium = "0.16.0"
log = "0.3"
redpitaya-scpi = "0.4"

[dependencies.conrod]
version="0.51"
features=["glium", "winit"]
